import { Clinic, PatientInquiry } from "./types";

export const clinics: Clinic[] = [
  { name: "HealthCore Austin Central", city: "Austin", state: "TX", phone: "(512) 340-8800", openingHours: ["Mo-Fr 07:00-20:00", "Sa 09:00-15:00"] },
  { name: "HealthCore Austin North", city: "Austin", state: "TX", phone: "(512) 340-8810", openingHours: ["Mo-Fr 08:00-19:00"] },
  { name: "HealthCore San Antonio", city: "San Antonio", state: "TX", phone: "(210) 720-4400", openingHours: ["Mo-Fr 08:00-18:00", "Sa 09:00-13:00"] },
  { name: "HealthCore Miami", city: "Miami", state: "FL", phone: "(305) 510-7700", openingHours: ["Mo-Fr 07:00-20:00", "Sa 09:00-16:00"] },
  { name: "HealthCore Orlando", city: "Orlando", state: "FL", phone: "(407) 892-6600", openingHours: ["Mo-Fr 08:00-18:00"] },
  { name: "HealthCore Atlanta", city: "Atlanta", state: "GA", phone: "(404) 330-9900", openingHours: ["Mo-Fr 08:00-19:00"] },
];

export const patientInquiries: PatientInquiry[] = [
  {
    firstName: "Maria",
    lastName: "Gomez",
    dateOfBirth: "1985-04-12",
    email: "maria.gomez@example.com",
    phone: "+1 512 555 0101",
    preferredLanguage: "Spanish",
    preferredClinic: "HealthCore Austin Central",
    preferredDate: "2026-07-15",
    preferredTime: "Morning (7am-12pm)",
    serviceType: "Primary Care",
    newPatient: false,
    hasInsurance: true,
    insuranceProvider: "BlueCross",
    insuranceMemberId: "BC123456",
    healthConcern: "Follow-up visit for blood pressure monitoring and medication review.",
    contactConsent: true,
    patientId: "HC-A3F291",
  },
  {
    firstName: "John",
    lastName: "Smith",
    dateOfBirth: "1990-01-01",
    email: "john.smith@example.com",
    phone: "+1 305 555 0110",
    preferredLanguage: "English",
    preferredClinic: "HealthCore Austin North",
    preferredDate: "2026-07-20",
    preferredTime: "Afternoon (12pm-5pm)",
    serviceType: "Chronic Disease Management",
    newPatient: true,
    hasInsurance: false,
    healthConcern: "Managing type 2 diabetes, need updated treatment plan.",
    contactConsent: true,
  },
  {
    firstName: "Sofia",
    lastName: "Ramirez",
    dateOfBirth: "2015-06-20",
    email: "sofia.parent@example.com",
    phone: "+1 305 555 0122",
    preferredLanguage: "Spanish",
    preferredClinic: "HealthCore Miami",
    preferredDate: "2026-07-18",
    preferredTime: "Evening (5pm-8pm)",
    serviceType: "Paediatric Care",
    newPatient: true,
    hasInsurance: true,
    insuranceProvider: "Aetna",
    insuranceMemberId: "AET789012",
    healthConcern: "Routine check-up and vaccination schedule review for child.",
    contactConsent: true,
  },
  {
    firstName: "Carlos",
    lastName: "Fernandez",
    dateOfBirth: "1975-09-09",
    email: "carlos.fernandez@example.com",
    phone: "+1 210 555 0133",
    preferredLanguage: "English",
    preferredClinic: "HealthCore San Antonio",
    preferredDate: "2026-07-22",
    preferredTime: "Evening (5pm-8pm)",
    serviceType: "Specialist Consultation",
    newPatient: false,
    hasInsurance: false,
    healthConcern: "Referral needed for cardiology consultation, irregular heartbeat.",
    contactConsent: true,
    patientId: "HC-B4X778",
  },
  {
    firstName: "Ana",
    lastName: "Lopez",
    dateOfBirth: "1960-03-03",
    email: "ana.lopez@example.com",
    phone: "+1 407 555 0144",
    preferredLanguage: "Spanish",
    preferredClinic: "HealthCore Orlando",
    preferredDate: "2026-07-25",
    preferredTime: "Morning (7am-12pm)",
    serviceType: "Preventive Health",
    newPatient: true,
    hasInsurance: true,
    insuranceProvider: "Cigna",
    insuranceMemberId: "CIG445566",
    healthConcern: "Annual physical exam and general wellness screening requested.",
    contactConsent: true,
  },
  {
    firstName: "Emma",
    lastName: "Davis",
    dateOfBirth: "1992-05-18",
    email: "emma.davis@example.com",
    phone: "+1 404 555 0155",
    preferredLanguage: "English",
    preferredClinic: "HealthCore Atlanta",
    preferredDate: "2026-07-28",
    preferredTime: "Afternoon (12pm-5pm)",
    serviceType: "Women's Health",
    newPatient: false,
    hasInsurance: false,
    healthConcern: "Annual gynaecological exam and consultation on birth control options.",
    contactConsent: true,
    patientId: "HC-C9K102",
  },
  {
    firstName: "Miguel",
    lastName: "Torres",
    dateOfBirth: "2008-11-11",
    email: "miguel.torres@example.com",
    phone: "+1 512 555 0166",
    preferredLanguage: "Spanish",
    preferredClinic: "HealthCore Austin Central",
    preferredDate: "2026-07-30",
    preferredTime: "Morning (7am-12pm)",
    serviceType: "Mental Health",
    newPatient: true,
    hasInsurance: true,
    insuranceProvider: "UnitedHealth",
    insuranceMemberId: "UH334455",
    healthConcern: "Experiencing anxiety related to school and would like counselling support.",
    contactConsent: true,
  },
  {
    firstName: "Laura",
    lastName: "Chen",
    dateOfBirth: "1988-07-07",
    email: "laura.chen@example.com",
    phone: "+1 305 555 0177",
    preferredLanguage: "English",
    preferredClinic: "HealthCore Miami",
    preferredDate: "2026-08-02",
    preferredTime: "Evening (5pm-8pm)",
    serviceType: "Mental Health",
    newPatient: false,
    hasInsurance: false,
    healthConcern: "Follow-up therapy session for ongoing stress management.",
    contactConsent: true,
    patientId: "HC-D2M560",
  },
];